version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - MAPBIOMAS_TOKEN=${MAPBIOMAS_TOKEN}
    volumes:
      - ./backend:/app
    env_file:
      - ./.env  # Arquivo .env na raiz do projeto
    restart: unless-stopped
    networks:
      - aira-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - aira-network

networks:
  aira-network:
    driver: bridge